NEXUS-4432: Add nexus scripts in top of bin dir. Move executable & lis around to support the old and new scripts.

diff --git a/nexus/nexus-oss-webapp/src/main/assembly/content/bin/nexus b/nexus/nexus-oss-webapp/src/main/assembly/content/bin/nexus
--- a/nexus/nexus-oss-webapp/src/main/assembly/content/bin/nexus
+++ b/nexus/nexus-oss-webapp/src/main/assembly/content/bin/nexus
@@ -15,8 +15,8 @@ APP_NAME="nexus"
 APP_LONG_NAME="Nexus OSS"
 
 # Wrapper
-WRAPPER_CMD="../exec/wrapper-solaris-sparc-64"
-WRAPPER_CONF="../conf/wrapper.conf"
+WRAPPER_CMD="jsw/exec/wrapper"
+WRAPPER_CONF="jsw/conf/wrapper.conf"
 
 # Priority at which to run the wrapper.  See "man nice" for valid priorities.
 #  nice is only used if a priority is specified.
@@ -158,19 +158,28 @@ esac
 
 # Resolve the architecture
 DIST_ARCH=`uname -p | tr [:upper:] [:lower:] | tr -d [:blank:]`
+DIST_BITS=32
 if [ "$DIST_ARCH" = "unknown" ]
 then
     DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
 fi
 case "$DIST_ARCH" in
-    'amd64' | 'athlon' | 'ia32' | 'ia64' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
+    'athlon' | 'ia32' | 'i386' | 'i486' | 'i586' | 'i686')
         DIST_ARCH="x86"
+        ;;
+    'amd64' | 'x86_64' | 'ia64')
+        DIST_ARCH="x86"
+        DIST_BITS=64
         ;;
     'ip27')
         DIST_ARCH="mips"
         ;;
-    'power' | 'powerpc' | 'power_pc' | 'ppc64')
+    'power' | 'powerpc' | 'power_pc')
         DIST_ARCH="ppc"
+        ;;
+    'ppc64')
+        DIST_ARCH="ppc"
+        DIST_BITS=64
         ;;
     'pa_risc' | 'pa-risc')
         DIST_ARCH="parisc"
@@ -183,6 +192,16 @@ case "$DIST_ARCH" in
         ;;
 esac
 
+# Extra architecture detection
+case "$DIST_OS" in
+    'macosx')
+        if [ `sysctl hw.cpu64bit_capable | awk '{ print $2 }'` = '1' ]; then
+            DIST_BITS=64
+        fi
+        DIST_ARCH='universal'
+        ;;
+esac
+
 outputFile() {
     if [ -f "$1" ]
     then
@@ -192,62 +211,72 @@ outputFile() {
     fi
 }
 
-# Decide on the wrapper binary to use.
-# If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
-#  platforms, if the 64-bit binary exists then the distribution most
-#  likely wants to use long names.  Otherwise, look for the default.
-# For macosx, we also want to look for universal binaries.
-WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-if [ -x "$WRAPPER_TEST_CMD" ]
-then
-    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-else
-    if [ "$DIST_OS" = "macosx" ]
+ignoreThisStuffForNow() {
+    # Decide on the wrapper binary to use.
+    # If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
+    #  platforms, if the 64-bit binary exists then the distribution most
+    #  likely wants to use long names.  Otherwise, look for the default.
+    # For macosx, we also want to look for universal binaries.
+    WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+    if [ -x "$WRAPPER_TEST_CMD" ]
     then
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
-        if [ -x "$WRAPPER_TEST_CMD" ]
+        WRAPPER_CMD="$WRAPPER_TEST_CMD"
+    else
+        if [ "$DIST_OS" = "macosx" ]
         then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
+            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
+            if [ -x "$WRAPPER_TEST_CMD" ]
+            then
+                WRAPPER_CMD="$WRAPPER_TEST_CMD"
+            else
+                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+                if [ -x "$WRAPPER_TEST_CMD" ]
+                then
+                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
+                else
+                    WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
+                    if [ -x "$WRAPPER_TEST_CMD" ]
+                    then
+                        WRAPPER_CMD="$WRAPPER_TEST_CMD"
+                    else
+                        if [ ! -x "$WRAPPER_CMD" ]
+                        then
+                            echo "Unable to locate any of the following binaries:"
+                            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+                            outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
+                            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+                            outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
+                            outputFile "$WRAPPER_CMD"
+                            exit 1
+                        fi
+                    fi
+                fi
+            fi
         else
             WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
             if [ -x "$WRAPPER_TEST_CMD" ]
             then
                 WRAPPER_CMD="$WRAPPER_TEST_CMD"
             else
-                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-                if [ -x "$WRAPPER_TEST_CMD" ]
+                if [ ! -x "$WRAPPER_CMD" ]
                 then
-                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-                else
-                    if [ ! -x "$WRAPPER_CMD" ]
-                    then
-                        echo "Unable to locate any of the following binaries:"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
-                        outputFile "$WRAPPER_CMD"
-                        exit 1
-                    fi
+                    echo "Unable to locate any of the following binaries:"
+                    outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+                    outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+                    outputFile "$WRAPPER_CMD"
+                    exit 1
                 fi
             fi
         fi
-    else
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            if [ ! -x "$WRAPPER_CMD" ]
-            then
-                echo "Unable to locate any of the following binaries:"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                outputFile "$WRAPPER_CMD"
-                exit 1
-            fi
-        fi
     fi
+}
+
+TEST_WRAPPER_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
+if [ -x "$TEST_WRAPPER_CMD" ]; then
+    WRAPPER_CMD="$TEST_WRAPPER_CMD"
+else
+    echo "Missing platform binary: $TEST_WRAPPER_CMD"
+    exit 1
 fi
 
 # Build the nice clause
@@ -360,12 +389,17 @@ getpid() {
                 #  common is during system startup after an unclean shutdown.
                 # The ps statement below looks for the specific wrapper command running as
                 #  the pid.  If it is not found then the pid file is considered to be stale.
-                if [ "$DIST_OS" = "solaris" ]
-                then
-                    pidtest=`$PSEXE ww $pid | grep "$WRAPPER_CMD" | tail -1`
-                else
-                    pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
-                fi                
+                case "$DIST_OS" in
+                    'macosx')
+                        pidtest=`$PSEXE -ww -p $pid -o command | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                    'solaris')
+                        pidtest=`$PSEXE ww $pid | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                    *)
+                        pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                esac
                 if [ "X$pidtest" = "X" ]
                 then
                     # This is a stale pid file.
